packages:
  base_image: !include satellite1.yaml
  mmwave_ld2450: !include common/mmwave_ld2450.yaml

satellite1_radar: !remove

text_sensor:
  - id: !remove radar_detected_text

esphome:
  name: ${node_name}
  project:
    name: ${company_name}.${project_name}
    version: ${esp32_fw_version}+ld2450

update:
  - platform: http_request
    name: None
    id: !extend update_http_request
    source: https://raw.githubusercontent.com/FutureProofHomes/Documentation/refs/heads/main/manifest.ld2450.json

switch:
  - platform: template
    id: !extend beta_firmware
    name: Beta firmware
    icon: "mdi:test-tube"
    entity_category: diagnostic
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log: "OTA updates set to use Beta firmware"
      - lambda: id(update_http_request).set_source_url("https://raw.githubusercontent.com/FutureProofHomes/Documentation/refs/heads/main/manifest-beta.ld2450.json");
      - component.update: update_http_request
    on_turn_off:
      - logger.log: "OTA updates set to use Production firmware"
      - lambda: id(update_http_request).set_source_url("https://raw.githubusercontent.com/FutureProofHomes/Documentation/refs/heads/main/manifest.ld2450.json");
      - component.update: update_http_request
