substitutions:
  ext_comp_repo_url: https://github.com/FutureProofHomes/Satellite1-ESPHome
  ext_comp_repo_ref: staging

external_components:
  - source:
      type: git
      url: ${ext_comp_repo_url}
      ref: ${ext_comp_repo_ref}
    components:
      - fusb302b
      - i2s_audio
      - memory_flasher
      - pcm5122
      - satellite1
      - tas2780

  - source:
      # https://github.com/esphome/esphome/pull/12429
      type: git
      url: https://github.com/esphome/esphome
      ref: ff8ce89556748509d7ee8724e12d9d43d3c8c1e8
    refresh: 300s
    components: [http_request]
