substitutions:
  ext_comp_repo_url: https://github.com/FutureProofHomes/Satellite1-ESPHome
  ext_comp_repo_ref: staging

external_components:
  - source:
      type: git
      url: ${ext_comp_repo_url}
      ref: ${ext_comp_repo_ref}
    refresh: 1s
    components:
      - fusb302b
      - i2s_audio
      - memory_flasher
      - satellite1
      - satellite1_radar
      - tas2780
