microphone:
  - platform: satellite1
    id: sat1_mics
    sample_rate: 48000
    i2s_din_pin: GPIO15
    bits_per_sample: 32bit
    channel: stereo
    pdm: false
    adc_type: external
    i2s_audio_id: i2s_shared
