external_components:
  # ESPHome PRs for sendspin and related features
  - source:
      # https://github.com/esphome/esphome/pull/14933
      type: git
      url: https://github.com/kahrendt/esphome
      ref: 7a6cf5c8472b7e2fa18ee0fc314f66a80d249e32
    components: [const, media_source, sendspin]
    refresh: 300s

http_request:

sendspin:
  id: sendspin_hub
  task_stack_in_psram: true

media_source:
  - platform: sendspin
    id: sendspin_media_source

media_player:
  - platform: sendspin
    id: sendspin_group_media_player

  - platform: speaker_source
    id: !extend external_media_player
    media_pipeline:
      sources:
        - sendspin_media_source
