sendspin:
  id: sendspin_hub
  task_stack_in_psram: true

media_source:
  - platform: sendspin
    id: sendspin_media_source

media_player:
  - platform: sendspin
    id: sendspin_group_media_player

  - platform: speaker_source
    id: !extend external_media_player
    media_pipeline:
      sources:
        - sendspin_media_source
